# Generated by Django 4.2.1 on 2023-07-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LusherColorPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color_pair",
                    models.CharField(max_length=100, verbose_name="Пара цветов"),
                ),
                ("interpretation", models.TextField(verbose_name="Интерпретация")),
            ],
            options={
                "verbose_name": "Пара цветов",
                "verbose_name_plural": "Пары цветов",
            },
        ),
    ]
